Add extern for goog. (#3417)
As of closure-compiler-v20191027.jar the compile now breaks due to a lack of ‘goog’ being defined.

../../temp_core/constants.js:24: ERROR - [JSC_UNDEFINED_VARIABLE] variable goog is undeclared
goog.provide('Blockly.constants');
^^^^

1 error(s), 0 warning(s)
Compiler exit code: 1
Compilation FAIL.

Upgrade closure compiler to v20191027